project:
  type: website
  output-dir: docs

website:
  title: "Erfassung und Monitoring von Wildtieren"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - text: Vorlesungen
        menu:
          - text: "Einführung"
          - href: content/vorlesungen/01-vorlesung.qmd
            text: "01. Einführung"
          - href: content/vorlesungen/02-vorlesung.qmd
            text: "02. Methoden"
          - text: "-------"
          - text: "Vorkommen"
          - text: "03. Wo kommt eine Art vor?"
          - text: "04. Vorkommen vorhersagen"
          - text: "05. Occupancy Modelle"
          - text: "06. Was, wenn man nicht alle sieht?"
          - text: "----"
          - text: "Abundanz"
          - text: "07. Populationsgrößenschätzung (Distance sampling)"
          - text: "08. Fang-Wiederfang-Methoden"
          - text: "----"
          - text: "Telemetrie"
          - text: "09. Einführung"
          - text: "10. Streifgebiete"
          - text: "11. Habitatselektion 1"
          - text: "12. Habitatselektion 2"
      - text: Übungen
        menu:
          - text: "**Grundlagen in R**"
          - href: content/uebungen/uebung_w1.qmd
            text: "1. Einführung in R"
          - text: "-----"
          - text: "**Occupancy**"
          - href: content/uebungen/uebung_w2.qmd
            text: "2. Bayes"
#          - href: content/uebungen/uebung_w3.qmd
#            text: "3. Likelihood"
#          - href: content/uebungen/uebung_w4.qmd
#            text: "4. Lineares Model"
#          - href: content/uebungen/uebung_w5.qmd
#            text: "5. Generalisiertes Lineares Model"
#          - href: content/uebungen/uebung_w6.qmd
#            text: "6. Occupancy Model"
      - text: Prüfungsleistungen
        href: content/pruefung/pruefungen.qmd


format:
  html:
    lang: de
    theme: litera
    toc: true
    code-fold: false
    #code-tools: true
    code-summary: "Lösung anzeigen"
    css: styles.css
#    include-before-body: _setup.qmd
