

# Vorlesung

- Herdenschutz gegen Wölfe (siehe unten)
- [Harmonisierung von Daten (Fotofallen Aufgabe)](/content/slides/pdf/fotofallen.pdf){target="_blank"}
- [Vorkommen von Arten](/content/slides/01/03-vorkommen.html){target="_blank"}
- [Übung: Beta-Binomial Modell](/content/uebungen/uebung_w2.html){target="_blank"}
- [Übung: Die Sache mit der Likelihood](/content/uebungen/uebung_w3.html){target="_blank"}

## Herdenschutz gegen Wolfsübergriffe

Die Aufgabenstellung: 

> Nicht nur das, Studien aus Slowenien, Frankreich und Schweden belegen, dass die weitgehende Freigabe der Jagd auf Wölfe nicht zielführend hinsichtlich des Schutzes von Weidetieren ist. Der ist ausschließlich durch geeignete Herdenschutzmaßnahmen zu gewährleisten. Dafür gibt es zahlreiche Beispiele in Deutschland. Weidetiere durch das nun beschlossene Jagdgesetz zu schützen ist ein Trugschluss. Weidetierhalter, die sich darauf verlassen, werden verlassen sein.

Quelle: <https://www.wildtierschutz-deutschland.de/single-post/wolf-im-bundesjagdgesetz>

In dem Artikel ist von Studien aus Slowenien, Frankreich und Schweden die Rede. Finden Sie eine oder mehrere dieser Studien, was sagen sie aus?

In [Evidenzbasiertes Wildtiermanagement](https://www.springerprofessional.de/evidenzbasiertes-wildtiermanagement/23955592) Kapitel 9 (Reinhardt et al. 2009): 

- Slowenien: Krofel M, Černe R, Jerina K (2011) Učinkovitost odstrela volkov (Canis lupus) kot ukrepa za zmanjševanje škode na domačih živalih — Effectiveness of wolf (Canis lupus) culling to reduce livestock depredations. Zb gozdarstva Lesar 95:11–22
- Schweden und Norwegen: Linnell JDC, Cretois B (2018) Research for AGRI Committee – The revival of wolves and other large predators and its impact on farmers and their livelihood in rural regions of Europe. European Parliament. Policy Department for Structural and Cohesion Policies, Brussels
- Frankreich: Plisson A-L (2011) Étude de la vulnérabilité des troupeaux ovins à la prédation du loup dans le Parc naturel régional du Queyras. Mémoire diplôme EPHE

Plisson 2011 und Krofel et al. 2011 konnte ich nicht lesen (Sprache). Linell and Cretois war verfügbar (<https://www.europarl.europa.eu/cmsdata/191585/IPOL_STU(2018)617488_EN%20AGRI-original.pdf>; aber 106S): 



# Folien


- [Alle Folien (html)](/content/slides/01/02-vorkommen.html){target="_blank"}
- [Alle Folien (pdf)](/content/slides/pdf/vl-3.pdf){target="_blank"}
- [Harmonisierung von Fotofallendaten](/content/slides/pdf/fotofallen.pdf){target="_blank"}

# Bis nächsten Einheit

Lesen Sie die Einleitung (I Introduction) von [Boyd et al. 2023](https://onlinelibrary.wiley.com/doi/full/10.1111/brv.12961) und überlegen Sie sich Antowrten zu folgenden Fragen: 

- Was ist das Ziel des Papers?
- Was sind EBVs?
- Wofür steht GEO-BON und was ist es?




