---
title: "Prüfungsleistungen"
date: last-modified
---

Die Benotung für dieses Modul erfolgt anhand einer strukturierten Hausarbeit. Um für die Hausarbeit zugelassen zu werden, muss eine Prüfungsvorleistung absolviert werden, darin werden die wichtigsten Konzepte, Methoden und Begriffe der Vorlesung in einem Multiple-Choice-Test abgefragt. 

Für die Hausarbeit verwenden Sie einen bereits erhobenen Datensatz. Es ist auch zulässig eine beretis durchgeführte Studie zu wiederholen. Nähere Details zur Hausarbeit fogen ab Woche 8 des Semesters. 

# Prüfungsvorleistung

## Literatur
Eine Vertrautheit mit folgenden Veröffentlichungen erwarte ich:

1. Zu den FFH-Berichten: Müller et al. 2019: <https://www.researchgate.net/publication/349721250_Der_nationale_Bericht_2019_zu_Lebensraumtypen_und_Arten_der_FFH-Richtlinie_-_ein_Uberblick_uber_die_Ergebnisse>

2. Zu Monitoring und Occupancy-Modellen: Boyd et al. 2023: <https://onlinelibrary.wiley.com/doi/full/10.1111/brv.12961>

3. Sliwinski et al. 2021 [Comparison of spotlighting monitoring data of European brown hare (Lepus europaeus) relative population densities with infrared thermography in agricultural landscapes in Northern Germany](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0254084)
4. Ausband et al. 2022 [Estimating wolf abundance from cameras](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.3933)
5. Telemetriestudie

Sie haben die Veröffentlichungen gelesen, kenne ungefähr den Inhalt und finden Antworten auf spezifische Fragen schnell. Es werden keine Fragen zu technischen/statistischen Details gestellt.

## Terminologie
Ich erwarte, dass Sie die alle Begriffe dieser Liste kennen und verwenden können:

::: {.columns}

::: {.column width="50%"}
### Woche 1

1. Monitoring
2. Statistische Inferenz
3. Zustandsvariable
4. EU-Verordnung
5. EU-Richtlinie
6. FFH-Richtlinie
7. Anhänge der FFH-Richtlinie
8. Ramsar Konvention
9. Berner Konvention
10. Relative vs. absolute Pfade
:::

::: {.column width="50%"}
### Woche 2

1. Likelihood
2. Posterior
3. Prior
4. Parameter
5. Bayesiansche Statistik
6. Frequentistische Statistik
7. Gamma Verteilung
8. Scalp Kriterien
9. Citizen Science
10. PIT-Tags
:::

:::

::: {.columns}

::: {.column width="50%"}
### Woche 3

1. Autökologie
2. Fundamentale und realisierte Nische
3. Zufallsvariable
4. Stenöke Arten
5. Euryöke Arten
6. Habitat
7. Biotop
8. Habitatwahl
9. Limitierender Faktor
10. Statistische vs. meachnistische Modelle
11. Grundgesamtheit
12. Stichprobe
13. Verteilungen (Binomial, Poisson, Normal, Beta)
:::

::: {.column width="50%"}
### Woche 4
1. Zufallsvariable
2. GBIF 
3. EVBs
4. GEO-BON
5. Kovariate
6. Lineares Modell
7. Intercept
8. Steigung (*Slope*)
9. Erwartungswert

:::
:::

::: {.columns}

::: {.column width="50%"}
### Woche 5

1. Linkfunktion
2. Linearerprädiktor
3. Zielverteilung
4. Unterschied GLM und LM
5. Komponenten eines GLMs
6. Belegrate/Occupancy ($\psi$)
7. Detektion ($p$)
8. Was ist eine README-Datei?
9. Wozu braucht man eine README-Datei
:::

::: {.column width="50%"}



:::
:::


## Statistik
Es werden **keine** R-Kenntnisse abgefragt, lediglich die Interpretation von Ergebnissen. 


# Prüfungsleistung

Die Prüfungsleistung besteht aus einer strukturierten Hausarbeit. 

Stellen Sie eine Hypothese/Erwartung  auf und analysieren Sie dazu einen bereits vorhandenen Datensatz.  

-	Analysen (40%)
-	Schriftliche Ausarbeitung (60%)


## Analysen
1. Code ist reproduzierbar. (60%)
2. Der Code ist ausreichend dokumentiert und logisch sinnvoll aufgebaut. 	(25%)
3. Es gibt eine README-Datei, die beschreibt, wie man den Code und die Analyse ausführen kann.	(15%)

## Hausarbeit

### Gliederung

| Was             | Bewertung | Detaillierte Bewertung |
|-----------------|-----------|------------------------|
| Einleitung      | 15 %      | 1. Worum geht es (1–2 Absätze); 30 %<br>2. Stand der Dinge (1 Absatz); 20 %<br>3. Ziel dieser Hausarbeit; 20 %<br>4. Literatur (3–5 peer-reviewed Veröffentlichungen); 30 % |
| Methoden        | 25 %      | 1. Datenquellen, wie wurden die Daten aufgenommen; 20 %<br>2. Modellbeschreibung (welches Modell wurde verwendet, wie wurde es parametrisiert); 40 %<br>3. Aufschreiben und beschreiben der Modellgleichung; 30 %<br>4. Richtige Zitation aller Software; 10 % |
| Ergebnisse      | 25 %      | - Beschreibung der Ergebnisse, die für die Fragestellung relevant sind; 20 %<br>- Zwei Abbildungen, die die Ergebnisse untermauern und das Modell visualisieren; 60 %<br>- Eine Tabelle, die für die Fragestellung relevante Rohdaten oder Modelloutput zusammenfasst 20 %|
| Diskussion      | 15 %      | Jeweils ein Absatz, der:<br>1. der, die Ergebnisse zusammenfasst und in Verbindung mit den Hypothese(n) bringt; 30 %<br>2. der, mögliche Schwachstellen, Erweiterungen etc. diskutiert; 30 %<br>3. der, die Ergebnisse im Kontext der aktuellen begutachteten Literatur (>2020) darstellt (3–5 Referenzen); 40 % |
| Referenzen      | 5 %       | Alle verwendeten Quellen (inkl. Software) sind in einem Literaturverzeichnis einheitlich zitiert |
| Zusammenfassung | 5 %       | Dem Text ist eine Zusammenfassung von einem Absatz vorangestellt (max. 200 Wörter) |
| Form            | 5 %       | Die Arbeit ist einheitlich und ansprechend formatiert |
| Ausdruck        | 5 %       | Die Arbeit ist verständlich und fehlerfrei geschrieben |


### Umfang 

In Summe sollte die Hausarbeit 10 bis 15 Seiten umfassen: 

Grob stelle ich mir die Aufteilung wie folgt vor: 

- Titelblatt, Zusammenfassung Literatur und evtl. Anhänge ca. 5 Seiten
- Einleitung 1 - 2 Seiten. 
- Methoden 2 - 3 Seiten
- Ergebnisse 2 - 3 Seiten
- Disusskon 1 - 2 Seiten. 


### Datenquellen

#### Veröffentlichungen

- Feldhasen	(Telemetrie) <https://figshare.com/articles/dataset/Urban_hare_data/30208969?file=58257865> und
<https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1002/wlb3.01513>
- Schneehuhn (Distance Sampling) <https://dataverse.no/file.xhtml?persistentId=doi:10.18710/V1NDV6/DYOWE6&version=1.0> und  <https://nsojournals.onlinelibrary.wiley.com/doi/10.1002/wlb3.01471>
- Schneehuhn (Distance Sampling) <https://datadryad.org/dataset/doi:10.5061/dryad.zgmsbccpj> und
<https://nsojournals.onlinelibrary.wiley.com/doi/10.1002/wlb3.01350>
- Puma (Kamerafallen)	<https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP3/QJKTYA> und < https://nsojournals.onlinelibrary.wiley.com/doi/10.1002/wlb3.01308>
- Weißwedelhirsch (Fang-Wiederfang) <https://datadryad.org/dataset/doi:10.5061/dryad.43j74d0> und < https://bioone.org/journals/annales-zoologici-fennici/volume-56/issue-1-6/086.056.0101/Estimating-Population-Density-of-the-White-Tailed-Deer-in-Finland/10.5735/086.056.0101.short>  
- HomeRange: A global database of mammalian home ranges: <https://onlinelibrary.wiley.com/doi/full/10.1111/geb.13625>
- The body size and temperature dependence of organismal locomotion: <https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.3114>
- Petroni et al. 2025 (Occupancy) Recolonization pattern of wolves in Northern Apennines, Central Italy: a Bayesian analysis using opportunistic and systematic data <https://cdnsciencepub.com/doi/10.1139/cjz-2025-0010>. *Daten und Code sind im Anhang*. 

#### Datenbanken

- GBIF für Vorkommensdaten: <https://www.gbif.org/>
- Movebank für Bewegungsdaten: <https://www.movebank.org/cms/webapp?gwt_fragment=page=search_map>
- Dryad <https://datadryad.org/>

